env:
  es2020: true
  node: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - prettier
rules:
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-var-requires': off
  '@typescript-eslint/ban-ts-comment': off
  '@typescript-eslint/no-explicit-any': off
